import fs from "node:fs";
import path from "node:path";
import type { Tool } from "../types.js";
import { JARVIS_PRESENTATIONS_DIR } from "../utils/paths.js";
import {
  fail,
  ok,
  optionalString,
  requireString,
} from "../utils/result.js";
import { slugifyFilename } from "../utils/macos.js";

interface SlideInput {
  title: string;
  bullets: string[];
}

function parseSlidesParam(params: Record<string, unknown>): SlideInput[] | undefined {
  const raw = params.slides;
  if (!Array.isArray(raw)) {
    return undefined;
  }
  const slides: SlideInput[] = [];
  for (const item of raw) {
    if (!item || typeof item !== "object") {
      continue;
    }
    const record = item as Record<string, unknown>;
    const title =
      typeof record.title === "string" && record.title.trim()
        ? record.title.trim()
        : "Slide";
    let bullets: string[] = [];
    if (Array.isArray(record.bullets)) {
      bullets = record.bullets.filter((b): b is string => typeof b === "string");
    } else if (typeof record.content === "string") {
      bullets = record.content
        .split(/\n+/)
        .map((line) => line.trim())
        .filter(Boolean);
    }
    slides.push({ title, bullets });
  }
  return slides.length > 0 ? slides : undefined;
}

function defaultSlides(title: string): SlideInput[] {
  return [
    { title, bullets: ["Generated by JarvisOS", "Edit slides in the output folder"] },
    { title: "Next steps", bullets: ["Add content", "Export or present in browser"] },
  ];
}

function buildOutlineMarkdown(title: string, slides: SlideInput[]): string {
  const lines = [`# ${title}`, ""];
  slides.forEach((slide, index) => {
    lines.push(`## ${index + 1}. ${slide.title}`);
    if (slide.bullets.length === 0) {
      lines.push("");
      return;
    }
    for (const bullet of slide.bullets) {
      lines.push(`- ${bullet}`);
    }
    lines.push("");
  });
  return lines.join("\n").trimEnd() + "\n";
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function buildHtmlDeck(title: string, slides: SlideInput[]): string {
  const slideSections = slides
    .map(
      (slide, index) => `
<section class="slide" data-index="${index + 1}">
  <h2>${escapeHtml(slide.title)}</h2>
  ${
    slide.bullets.length > 0
      ? `<ul>${slide.bullets.map((b) => `<li>${escapeHtml(b)}</li>`).join("")}</ul>`
      : "<p></p>"
  }
</section>`,
    )
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapeHtml(title)}</title>
  <style>
    * { box-sizing: border-box; }
    body {
      margin: 0;
      font-family: system-ui, -apple-system, sans-serif;
      background: #0b1020;
      color: #e8ecff;
    }
  header {
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      padding: 0.75rem 1.25rem;
      background: rgba(11, 16, 32, 0.9);
      border-bottom: 1px solid #2a3358;
      display: flex;
      justify-content: space-between;
      align-items: center;
      z-index: 2;
    }
    main { padding: 5rem 1.5rem 2rem; max-width: 960px; margin: 0 auto; }
    .slide {
      min-height: 70vh;
      padding: 2rem;
      margin-bottom: 2rem;
      border: 1px solid #2a3358;
      border-radius: 12px;
      background: linear-gradient(145deg, #121a33, #0f1528);
    }
    .slide h2 { margin-top: 0; font-size: 2rem; }
    .slide ul { font-size: 1.25rem; line-height: 1.6; }
    button {
      background: #3d5afe;
      color: white;
      border: none;
      border-radius: 8px;
      padding: 0.5rem 0.9rem;
      cursor: pointer;
    }
    button:disabled { opacity: 0.4; cursor: default; }
  </style>
</head>
<body>
  <header>
    <strong>${escapeHtml(title)}</strong>
    <div>
      <button id="prev" type="button">Prev</button>
      <span id="counter" style="margin: 0 0.5rem;"></span>
      <button id="next" type="button">Next</button>
    </div>
  </header>
  <main id="deck">
${slideSections}
  </main>
  <script>
    const slides = [...document.querySelectorAll('.slide')];
    let i = 0;
    const counter = document.getElementById('counter');
    const prev = document.getElementById('prev');
    const next = document.getElementById('next');
    function render() {
      slides.forEach((s, idx) => { s.style.display = idx === i ? 'block' : 'none'; });
      counter.textContent = (i + 1) + ' / ' + slides.length;
      prev.disabled = i === 0;
      next.disabled = i === slides.length - 1;
    }
    prev.addEventListener('click', () => { if (i > 0) { i--; render(); } });
    next.addEventListener('click', () => { if (i < slides.length - 1) { i++; render(); } });
    document.addEventListener('keydown', (e) => {
      if (e.key === 'ArrowRight' && i < slides.length - 1) { i++; render(); }
      if (e.key === 'ArrowLeft' && i > 0) { i--; render(); }
    });
    render();
  </script>
</body>
</html>
`;
}

function ensurePresentationDir(slug: string): string {
  const dir = path.join(JARVIS_PRESENTATIONS_DIR, slug);
  fs.mkdirSync(dir, { recursive: true });
  return dir;
}

export const presentationTool: Tool = {
  name: "presentation",
  description:
    "Generate a simple HTML slide deck or markdown outline in ~/JarvisOS/presentations/.",
  parameters: {
    type: "object",
    required: ["action"],
    properties: {
      action: {
        type: "string",
        enum: ["generate_html", "generate_outline", "list"],
        description: "generate_html | generate_outline | list",
      },
      title: { type: "string" },
      slides: {
        type: "array",
        description: "Array of { title, bullets[] } or { title, content }",
        items: { type: "object" },
      },
      limit: { type: "number", default: 20 },
    },
  },
  async execute(params) {
    try {
      const action = requireString(params, "action");

      if (action === "list") {
        fs.mkdirSync(JARVIS_PRESENTATIONS_DIR, { recursive: true });
        const limit =
          typeof params.limit === "number" && params.limit > 0
            ? Math.min(params.limit, 100)
            : 20;
        const entries = fs
          .readdirSync(JARVIS_PRESENTATIONS_DIR, { withFileTypes: true })
          .filter((d) => d.isDirectory())
          .map((d) => {
            const dir = path.join(JARVIS_PRESENTATIONS_DIR, d.name);
            const hasHtml = fs.existsSync(path.join(dir, "index.html"));
            const hasOutline = fs.existsSync(path.join(dir, "outline.md"));
            return { name: d.name, path: dir, hasHtml, hasOutline };
          })
          .slice(0, limit);
        return ok({
          presentations: entries,
          count: entries.length,
          directory: JARVIS_PRESENTATIONS_DIR,
        });
      }

      const title = requireString(params, "title");
      const slides = parseSlidesParam(params) ?? defaultSlides(title);
      const slug = slugifyFilename(title);
      const dir = ensurePresentationDir(slug);

      if (action === "generate_outline") {
        const filePath = path.join(dir, "outline.md");
        fs.writeFileSync(filePath, buildOutlineMarkdown(title, slides), "utf8");
        return ok(
          { title, slug, path: filePath, slideCount: slides.length, directory: dir },
          `Wrote outline to ${filePath}`,
        );
      }

      if (action === "generate_html") {
        const filePath = path.join(dir, "index.html");
        fs.writeFileSync(filePath, buildHtmlDeck(title, slides), "utf8");
        return ok(
          { title, slug, path: filePath, slideCount: slides.length, directory: dir },
          `Wrote HTML deck to ${filePath}`,
        );
      }

      return fail(`Unknown action: ${action}`);
    } catch (err) {
      return fail(err instanceof Error ? err.message : String(err));
    }
  },
};
