import fs from "node:fs/promises";
import path from "node:path";
import { expandPath } from "@jarvisos/tools";

export interface ProjectOpenResult {
  path: string;
  name: string;
  exists: boolean;
  packageManager?: "npm" | "pnpm" | "yarn" | "unknown";
  languages: string[];
  entryFiles: string[];
}

export interface ReadmeStubResult {
  path: string;
  written: boolean;
  content: string;
}

const LANG_EXTENSIONS: Record<string, string> = {
  ".ts": "TypeScript",
  ".tsx": "TypeScript",
  ".js": "JavaScript",
  ".jsx": "JavaScript",
  ".py": "Python",
  ".go": "Go",
  ".rs": "Rust",
  ".java": "Java",
};

async function detectLanguages(dir: string, depth = 0): Promise<Set<string>> {
  const langs = new Set<string>();
  if (depth > 2) return langs;

  let entries;
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return langs;
  }

  for (const entry of entries) {
    if (entry.name.startsWith(".") || entry.name === "node_modules") continue;
    const full = path.join(dir, entry.name);
    if (entry.isFile()) {
      const ext = path.extname(entry.name).toLowerCase();
      const lang = LANG_EXTENSIONS[ext];
      if (lang) langs.add(lang);
    } else if (entry.isDirectory() && depth < 2) {
      for (const l of await detectLanguages(full, depth + 1)) {
        langs.add(l);
      }
    }
  }
  return langs;
}

export async function openProject(projectPath: string): Promise<ProjectOpenResult> {
  const resolved = expandPath(projectPath);
  let exists = true;
  try {
    await fs.access(resolved);
  } catch {
    exists = false;
  }

  const name = path.basename(resolved);
  let packageManager: ProjectOpenResult["packageManager"] = "unknown";
  const checks: [string, ProjectOpenResult["packageManager"]][] = [
    ["pnpm-lock.yaml", "pnpm"],
    ["yarn.lock", "yarn"],
    ["package-lock.json", "npm"],
  ];
  for (const [file, pm] of checks) {
    try {
      await fs.access(path.join(resolved, file));
      packageManager = pm;
      break;
    } catch {
      // continue
    }
  }

  const languages = exists ? [...(await detectLanguages(resolved))] : [];
  const entryCandidates = ["package.json", "README.md", "src/index.ts", "main.py", "go.mod"];
  const entryFiles: string[] = [];
  for (const f of entryCandidates) {
    try {
      await fs.access(path.join(resolved, f));
      entryFiles.push(f);
    } catch {
      // skip
    }
  }

  return {
    path: resolved,
    name,
    exists,
    packageManager: exists ? packageManager : undefined,
    languages,
    entryFiles,
  };
}

export async function generateReadmeStub(projectPath: string): Promise<ReadmeStubResult> {
  const project = await openProject(projectPath);
  const readmePath = path.join(project.path, "README.md");

  const content = `# ${project.name}

> Generated by JarvisOS coding assistant (stub).

## Overview

Describe what this project does.

## Tech stack

${project.languages.length ? project.languages.map((l) => `- ${l}`).join("\n") : "- (detect languages by scanning src/)"}

## Setup

\`\`\`bash
# ${project.packageManager ?? "npm"} install
\`\`\`

## Development

\`\`\`bash
# add dev/start scripts from package.json
\`\`\`

## License

TBD
`;

  let written = false;
  try {
    await fs.access(readmePath);
  } catch {
    if (project.exists) {
      await fs.writeFile(readmePath, content, "utf8");
      written = true;
    }
  }

  return { path: readmePath, written, content };
}
